[project]
name = "matmaster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.10.0",
    "opik>=1.8.19",
    "bohr-agent-sdk==0.1.101",
    "oss2>=2.18.0",
    "aiofiles>=24.1.0",
    "pymysql>=1.1.1",
    "anyio>=4.10.0",
    "pytest-asyncio>=1.1.0",
    "litellm>=1.74.15.post2",
    "langgraph>=0.6.6",
    "langchain-azure-ai>=0.1.4",
    "langchain-litellm>=0.2.2",
    "loguru>=0.7.3",
    "mem0ai>=0.1.116",
    "langsmith>=0.4.20",
    "langchain[azure-ai,openai]>=0.3.27",
    "ipykernel>=6.30.1",
    "pip>=25.2",
    "langchain-tavily>=0.2.11",
]

[tool.setuptools]
packages = ["agents"]  # 明确指定只包含 agents 包

[tool.hatch.build.targets.wheel]
packages = ["agents"]
