name: Update pre-commit hooks

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5

      - name: Update pre-commit hooks
        uses: creyD/pre-commit-update@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: 'dependencies'
