name: Update pre-commit hooks

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Update pre-commit hooks and create PR
        run: |
          # 更新 hooks
          pre-commit autoupdate

          # 检查是否有变化
          if git diff --exit-code .pre-commit-config.yaml; then
            echo "No updates available"
            exit 0
          fi

          # 配置 git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # 提交更改
          git add .pre-commit-config.yaml
          git commit -m "chore: update pre-commit hooks"
          git push origin HEAD:update-pre-commit-hooks

          # 使用 GitHub CLI 创建 PR（需要先设置 GH_TOKEN）
          echo "Please create PR manually or setup GitHub CLI with token"

      - name: Output instructions
        if: failure()
        run: |
          echo "Changes were made but PR creation failed."
          echo "Please manually create a PR from the update-pre-commit-hooks branch"
