name: Update pre-commit hooks

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日 UTC 时间 00:00
  workflow_dispatch:      # 允许手动触发

permissions:
  contents: write
  pull-requests: write

jobs:
  update-pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录和分支

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Update pre-commit hooks
        run: pre-commit autoupdate

      - name: Check for changes
        id: changes
        run: |
          if git diff --exit-code .pre-commit-config.yaml; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            git diff .pre-commit-config.yaml
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update pre-commit hooks"
          title: "chore: update pre-commit hooks"
          body: |
            Automated update of pre-commit hooks via pre-commit autoupdate.

            **Changes made:**
            - Updated versions in .pre-commit-config.yaml
          branch: "update/pre-commit-hooks-$(date +%s)"
          base: main  # 根据你的默认分支修改，可能是 main 或 master
          labels: "dependencies"
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
