name: Update pre-commit hooks

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Update pre-commit hooks
        run: pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update pre-commit hooks"
          title: "chore: update pre-commit hooks"
          body: |
            Automated update of pre-commit hooks via pre-commit autoupdate.
          branch: "update/pre-commit-hooks"
          base: main
          labels: "dependencies"
          delete-branch: true
